#! /usr/bin/env python

from subprocess import call

for args in (['flush', '--noinput'],
             ['migrate'],
             ['loaddata', 'core/fixtures/emoji.json'],
             ['loaddata', 'core/fixtures/units.yaml'],
             ['loaddata', 'core/fixtures/tasks.yaml'],
             ['runserver']):
    call(['python', 'manage.py'] + args)
