#! /usr/bin/env bash

python manage.py migrate
python manage.py loaddata core/fixtures/emoji.json
python manage.py loaddata core/fixtures/units.yaml
python manage.py loaddata core/fixtures/tasks.yaml
python manage.py runserver
