# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180328_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'Continuing'), (2, 'Ended')]),
        ),
    ]
