# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180328_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='group',
            field=models.SmallIntegerField(choices=[(0, 'Happy'), (1, 'Notsohappy'), (2, 'Workingthinking'), (3, 'Fun')], default=0),
            preserve_default=False,
        ),
    ]
