# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emoji_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
